name: template
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  easy_localization: ^3.0.3
  flutter_screenutil: ^5.9.0
  easy_localization_loader: ^1.0.1+1
  easy_localization_loader:
    git: https://github.com/aissat/easy_localization_loader.git

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/translations/
